### ISSUE TITLE
ㅋㅋ

### ISSUE THREAD

**Issue by iceman-brandon** [sudo-G41/dlrjdjeldpTma#1]
이거 어디에씀이라니? ㅋㅋㅋ

**Comment by sudo-G41** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 아니 이걸 언제 보셨다나요... 허허...
잠깐 오늘(22년 1/16)만 필요해서 만든거라 이름 그렇게 지어봤습니다. 허허
